Repository octagram-kr/pollet-backend, pull requests merged in 2025-09, with the labels that each got.

#19 [FEATURE] OAuth2 연동 및 구현
  build.gradle
  src/main/java/com/octagram/pollet/auth/application/CustomUserOAuth2Service.java
  src/main/java/com/octagram/pollet/auth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/octagram/pollet/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/octagram/pollet/auth/infrastructure/CustomOAuth2User.java
  src/main/java/com/octagram/pollet/auth/infrastructure/OAuthAttributes.java
  src/main/java/com/octagram/pollet/auth/infrastructure/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/octagram/pollet/auth/infrastructure/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/octagram/pollet/auth/infrastructure/userinfo/OAuth2UserInfo.java
  src/main/java/com/octagram/pollet/gifticon/domain/model/GifticonCode.java
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/member/application/MemberService.java
  src/main/java/com/octagram/pollet/member/domain/Member.java
  src/main/java/com/octagram/pollet/member/domain/model/Member.java
  src/main/java/com/octagram/pollet/member/domain/model/type/AuthProvider.java
  src/main/java/com/octagram/pollet/member/domain/model/type/MemberStatus.java
  src/main/java/com/octagram/pollet/member/domain/model/type/Role.java
  src/main/java/com/octagram/pollet/member/infrastructure/MemberRepository.java
  src/main/java/com/octagram/pollet/member/infrastructure/MemberRepositoryCustom.java
  src/main/java/com/octagram/pollet/member/infrastructure/MemberRepositoryCustomImpl.java
  src/main/java/com/octagram/pollet/member/presentation/controller/MemberController.java
  src/main/java/com/octagram/pollet/member/presentation/dto/request/CreateMemberRequest.java
  src/main/java/com/octagram/pollet/survey/domain/model/Survey.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyPointHistory.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyResponse.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#26 [CHORE] 애플리케이션 컨테이너화를 위한 Dockerfile 작성
  .dockerignore
  Dockerfile
  build.gradle
Labels: ⚙️ chore

#35 [FEATURE] 문항 별 선택지 응답 엔티티 추가
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionOptionResponse.java
Labels: ✨ feature

#34 [FEATURE] JWT 설정
  build.gradle
  src/main/java/com/octagram/pollet/auth/application/CustomUserOAuth2Service.java
  src/main/java/com/octagram/pollet/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/octagram/pollet/auth/infrastructure/CustomOAuth2User.java
  src/main/java/com/octagram/pollet/global/config/RedisConfig.java
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/global/jwt/filter/JwtAuthFilter.java
  src/main/java/com/octagram/pollet/global/jwt/repository/TokenRedisRepository.java
  src/main/java/com/octagram/pollet/global/jwt/service/JwtService.java
  src/main/java/com/octagram/pollet/global/jwt/status/JwtErrorCode.java
  src/main/java/com/octagram/pollet/member/domain/model/Member.java
  src/main/java/com/octagram/pollet/member/infrastructure/MemberRepository.java
  src/main/resources/application-dev.yml
Labels: ⚙️ chore, ✨ feature

#36 [REFACTOR] 설문조사 도메인 MapStruct 적용 및 리팩토링
  src/main/java/com/octagram/pollet/gifticon/application/mapper/GifticonMapper.java
  src/main/java/com/octagram/pollet/gifticon/presentation/dto/response/GifticonProductInSurveyGetDetailResponse.java
  src/main/java/com/octagram/pollet/survey/application/SurveyService.java
  src/main/java/com/octagram/pollet/survey/application/mapper/SurveyMapper.java
  src/main/java/com/octagram/pollet/survey/application/mapper/TagMapper.java
  src/main/java/com/octagram/pollet/survey/domain/model/Question.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionOption.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionResponse.java
  src/main/java/com/octagram/pollet/survey/domain/model/Survey.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyPointHistory.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyResponse.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyTag.java
  src/main/java/com/octagram/pollet/survey/domain/model/Tag.java
  src/main/java/com/octagram/pollet/survey/domain/model/type/TargetGender.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyRepository.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyRepositoryCustom.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyTagRepository.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyTagRepositoryCustom.java
  src/main/java/com/octagram/pollet/survey/domain/repository/TagRepository.java
  src/main/java/com/octagram/pollet/survey/domain/status/SurveyErrorCode.java
  src/main/java/com/octagram/pollet/survey/domain/status/SurveySuccessCode.java
  src/main/java/com/octagram/pollet/survey/infrastructure/SurveyRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/infrastructure/SurveyTagRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/presentation/SurveyController.java
  src/main/java/com/octagram/pollet/survey/presentation/controller/SurveyController.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyDetailResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyGetDetailResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyGetResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/TagGetResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/TagResponse.java
Labels: ♻️ refactor

#38 [Refactor] 멤버 도메인 구조 리팩토링
  src/main/java/com/octagram/pollet/auth/application/CustomUserOAuth2Service.java
  src/main/java/com/octagram/pollet/global/jwt/service/JwtService.java
  src/main/java/com/octagram/pollet/member/application/MemberService.java
  src/main/java/com/octagram/pollet/member/domain/repository/MemberRepository.java
  src/main/java/com/octagram/pollet/member/domain/repository/MemberRepositoryCustom.java
  src/main/java/com/octagram/pollet/member/infrastructure/persistence/MemberRepositoryImpl.java
  src/main/java/com/octagram/pollet/member/presentation/MemberController.java
Labels: ♻️ refactor

#43 [FEATURE] 문항, 선택지 대상자 확인 여부 필드 추가
  src/main/java/com/octagram/pollet/survey/domain/model/Question.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionOption.java
  src/main/resources/data.sql
Labels: ✨ feature

#54 [FEATURE] 설문조사 도메인 엔티티 BaseEntity 상속
  src/main/java/com/octagram/pollet/survey/domain/model/Question.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionOption.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionOptionResponse.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionResponse.java
  src/main/java/com/octagram/pollet/survey/domain/model/Survey.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyPointHistory.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyResponse.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveyTag.java
  src/main/java/com/octagram/pollet/survey/domain/model/Tag.java
Labels: ✨ feature

#56 [FEATURE] BaseEntity 상속에 따른 더미데이터 필드 추가 및 수정
  src/main/resources/data.sql
Labels: ✨ feature

#62 [FIX] 삭제된 도메인에 대한 테스트코드 존재로 빌드 실패
  src/test/java/com/octagram/pollet/sample/domain/service/SampleServiceTest.java
Labels: 🔧 fix

#60 [TEST] OAuth2 테스트 페이지 작성
  build.gradle
  src/main/java/com/octagram/pollet/auth/application/CustomUserOAuth2Service.java
  src/main/java/com/octagram/pollet/auth/infrastructure/OAuthAttributes.java
  src/main/java/com/octagram/pollet/auth/infrastructure/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/octagram/pollet/auth/presentation/LoginPageController.java
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/global/jwt/filter/JwtAuthFilter.java
  src/main/java/com/octagram/pollet/member/domain/repository/MemberRepository.java
  src/main/resources/templates/login.html
Labels: ✅ test

#63 [FEATURE] 최근 등록된 설문 목록 조회 엔드포인트 구현
  src/main/java/com/octagram/pollet/survey/application/SurveyService.java
  src/main/java/com/octagram/pollet/survey/application/mapper/QuestionMapper.java
  src/main/java/com/octagram/pollet/survey/application/mapper/SurveyMapper.java
  src/main/java/com/octagram/pollet/survey/domain/repository/QuestionRepository.java
  src/main/java/com/octagram/pollet/survey/domain/repository/QuestionRepositoryCustom.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyRepository.java
  src/main/java/com/octagram/pollet/survey/domain/status/SurveyErrorCode.java
  src/main/java/com/octagram/pollet/survey/domain/status/SurveySuccessCode.java
  src/main/java/com/octagram/pollet/survey/infrastructure/QuestionRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/presentation/SurveyController.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/QuestionOptionListResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyGetRecentResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/TargetQuestionResponse.java
Labels: ✨ feature

#65 [FEATURE] 액세스 토큰 재발급 엔드포인트 구현
  src/main/java/com/octagram/pollet/auth/application/service/AuthService.java
  src/main/java/com/octagram/pollet/auth/application/service/CustomUserOAuth2Service.java
  src/main/java/com/octagram/pollet/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/octagram/pollet/auth/presentation/controller/AuthController.java
  src/main/java/com/octagram/pollet/auth/presentation/controller/LoginPageController.java
  src/main/java/com/octagram/pollet/auth/presentation/dto/response/AuthReissueResponse.java
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/global/jwt/filter/JwtAuthFilter.java
  src/main/java/com/octagram/pollet/global/jwt/repository/TokenRedisRepository.java
  src/main/java/com/octagram/pollet/global/jwt/service/JwtService.java
  src/main/java/com/octagram/pollet/global/jwt/status/JwtErrorCode.java
  src/main/java/com/octagram/pollet/member/domain/status/MemberErrorCode.java
Labels: ✨ feature

#66 [FEATURE] 설문 내부 이미지 업로드 엔드포인트 구현
  build.gradle
  src/main/java/com/octagram/pollet/global/aws/service/S3Service.java
  src/main/java/com/octagram/pollet/global/aws/status/S3ErrorCode.java
  src/main/java/com/octagram/pollet/global/config/AwsS3Config.java
  src/main/java/com/octagram/pollet/survey/presentation/SurveyController.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/request/SurveyImageGetRequest.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyImageGetResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyImageUploadResponse.java
  src/main/resources/application-dev.yml
Labels: ✨ feature

#67 [FEATURE] 설문 목록, 특정 설문 문항 목록 조회 엔드포인트 구현
  src/main/java/com/octagram/pollet/gifticon/application/mapper/GifticonMapper.java
  src/main/java/com/octagram/pollet/gifticon/presentation/dto/response/GifticonProductInSurveyFilterResponse.java
  src/main/java/com/octagram/pollet/survey/application/SurveyService.java
  src/main/java/com/octagram/pollet/survey/application/mapper/QuestionMapper.java
  src/main/java/com/octagram/pollet/survey/application/mapper/SurveyMapper.java
  src/main/java/com/octagram/pollet/survey/application/mapper/TagMapper.java
  src/main/java/com/octagram/pollet/survey/domain/model/Question.java
  src/main/java/com/octagram/pollet/survey/domain/model/Survey.java
  src/main/java/com/octagram/pollet/survey/domain/model/Tag.java
  src/main/java/com/octagram/pollet/survey/domain/model/type/FilterSortType.java
  src/main/java/com/octagram/pollet/survey/domain/model/type/TagType.java
  src/main/java/com/octagram/pollet/survey/domain/repository/QuestionRepositoryCustom.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyRepositoryCustom.java
  src/main/java/com/octagram/pollet/survey/infrastructure/QuestionRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/infrastructure/SurveyRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/presentation/SurveyController.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/request/SurveyFilterRequest.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/QuestionOptionResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/QuestionResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyFilterResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/TagInSurveyFilterResponse.java
  src/main/resources/data.sql
Labels: ✨ feature

#71 [REFACTOR] 엔티티 명 변경, 중복 DTO 정리 및 통합
  src/main/java/com/octagram/pollet/gifticon/application/mapper/GifticonMapper.java
  src/main/java/com/octagram/pollet/gifticon/presentation/dto/response/GifticonProductInSurveyFilterResponse.java
  src/main/java/com/octagram/pollet/gifticon/presentation/dto/response/GifticonProductResponse.java
  src/main/java/com/octagram/pollet/survey/application/SurveyService.java
  src/main/java/com/octagram/pollet/survey/application/mapper/QuestionMapper.java
  src/main/java/com/octagram/pollet/survey/application/mapper/SurveyMapper.java
  src/main/java/com/octagram/pollet/survey/application/mapper/TagMapper.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionOptionSubmission.java
  src/main/java/com/octagram/pollet/survey/domain/model/QuestionSubmission.java
  src/main/java/com/octagram/pollet/survey/domain/model/Survey.java
  src/main/java/com/octagram/pollet/survey/domain/model/SurveySubmission.java
  src/main/java/com/octagram/pollet/survey/domain/model/type/FilterSortType.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyRepository.java
  src/main/java/com/octagram/pollet/survey/infrastructure/QuestionRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/infrastructure/SurveyRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/presentation/SurveyController.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyFilterResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyGetDetailResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/SurveyGetResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/TagGetResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/TagInSurveyFilterResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/standard/QuestionOptionResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/standard/QuestionResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/standard/SurveyResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/standard/SurveyWithQuestionResponse.java
  src/main/java/com/octagram/pollet/survey/presentation/dto/response/standard/TagResponse.java
  src/main/resources/data.sql
Labels: ♻️ refactor

#77 [FEATURE] 로그아웃 엔드포인트 구현
  src/main/java/com/octagram/pollet/auth/application/service/AuthService.java
  src/main/java/com/octagram/pollet/auth/domain/status/AuthSuccessCode.java
  src/main/java/com/octagram/pollet/auth/presentation/controller/AuthController.java
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/global/jwt/service/JwtService.java
Labels: ✨ feature

#107 [FIX] 유효하지 않은 토큰 오류를 응답 본문에서 확인할 수 없는 현상 해결
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/global/jwt/filter/JwtExceptionFilter.java
Labels: 🔧 fix

#110 [FEATURE] 시큐리티 필터 엔드포인트 추가
  src/main/java/com/octagram/pollet/global/config/SecurityConfig.java
  src/main/java/com/octagram/pollet/global/jwt/filter/JwtAuthFilter.java
Labels: ✨ feature

#117 [CHORE] 프로덕션용 application.yml 생성
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#118 [RELEASE] ECR 업로드 워크플로우 테스트
  src/main/resources/application-prod.yml
Labels: 🚀 release

#122 [RELEASE] Actuator 엔드포인트 노출
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🚀 release

#123 [DOCS] README 작성
  README.md
Labels: 📄 docs

#127 [RELEASE] 설문조사 응답 동시성 테스트 반영
  src/main/java/com/octagram/pollet/member/application/service/MemberService.java
  src/main/java/com/octagram/pollet/member/domain/repository/PointRepository.java
  src/main/java/com/octagram/pollet/member/domain/repository/PointRepositoryCustom.java
  src/main/java/com/octagram/pollet/member/infrastructure/persistence/PointRepositoryImpl.java
  src/main/java/com/octagram/pollet/survey/application/service/SurveyService.java
  src/main/java/com/octagram/pollet/survey/domain/repository/SurveyRepositoryCustom.java
  src/main/java/com/octagram/pollet/survey/infrastructure/persistence/SurveyRepositoryImpl.java
  src/test/java/com/octagram/pollet/support/annotation/ServiceTest.java
  src/test/java/com/octagram/pollet/survey/application/service/SurveyServiceTest.java
  src/test/resources/application-test.yml
Labels: 🚀 release
